version: '3.8'

services:
  backend:
    build: ./heatHBack
    ports:
      - "8080:8080"
    networks:
      - appnet
  frontend:
    build: ./heatHFront/React-Web/web
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - backend

networks:
  appnet: