server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heath
    username: postgres
    password: 0e1fa2b1d9faa8fedc3aa9fe1d090635
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect