server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://34.40.43.87:5432/heath
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect