spring:
  datasource:
    url: jdbc:postgresql://34.40.43.87:5432/heath
    username: postgres
    password: 1001defbc42fdd73e6b2bc6308cd9000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: heath352.451@gmail.com
    password: rrkn cwwh zbet urak
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true